name: Build and Push Docker Image

# 1. Yeh pipeline kab chalega? (Jab code 'main' branch par push hoga)
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub humein ek free Ubuntu machine dega

    steps:
      # Step A: GitHub se aapka sara code is free machine mein copy karna
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step B: Docker Hub par automatic login karna
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step C: Image ko build aur push karna (Ek hi jhatke mein)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yasiralisiddiqui/my-flask-app:latest


